Changed directory to /rds/user/dh486/hpc-work/GNN_Work.

JobID: 23750962
======
Time: Sat  9 May 15:49:36 BST 2020
Running on master node: cpu-e-37
Current directory: /rds/user/dh486/hpc-work/GNN_Work

Nodes allocated:
================
cpu-e-37

numtasks=, numnodes=1, mpi_tasks_per_node=32 (OMP_NUM_THREADS=1)

Executing command:
==================
mpirun -npernode 32 -np 32 /home/dh486/gnn-env/bin/python /home/dh486/rds/hpc-work/GNN_Work/make_dataset.py

Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Looking for files...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Looking for files...
Processing...
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Checking backbone restraints on chromosome chr1
Chromosome length: 3848
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Added in 18 positive strand and 18 negative strand backbone contacts for chr1
Done!
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Checking backbone restraints on chromosome chr10
Chromosome length: 2552
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Added in 25 positive strand and 25 negative strand backbone contacts for chr10
Done!
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Checking backbone restraints on chromosome chr11
Chromosome length: 2378
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Added in 5 positive strand and 5 negative strand backbone contacts for chr11
Done!
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Checking backbone restraints on chromosome chr12
Chromosome length: 2343
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 192, in __init__
    self._task_handler.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/dh486/rds/hpc-work/GNN_Work/make_dataset.py", line 9, in <module>
    binSize = 50)
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 175, in __init__
    super(pop_HiC_Dataset, self).__init__(root + "{}".format(self.condition), transform, pre_transform)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/dh486/gnn-env/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/datasets.py", line 192, in process
    self.shape, self.binSize, self.chrlims, edge_index, edge_attr = p.make_ptg_pophic_edge_index(osp.join(self.raw_dir, '{}_{}kb.npz'.format(self.condition, self.binSize)))
  File "/rds/user/dh486/hpc-work/GNN_Work/utils/processing.py", line 167, in make_ptg_pophic_edge_index
    p = Pool()
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/software/master/python/3.6/lib/python3.6/multiprocessing/pool.py", line 182, in __init__
    self._worker_handler.start()
  File "/usr/local/software/master/python/3.6/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Added in 140 positive strand and 140 negative strand backbone contacts for chr12
Done!
Added in 140 positive strand and 140 negative strand backbone contacts for chr12
Done!
Added in 140 positive strand and 140 negative strand backbone contacts for chr12
Done!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31155,1],25]
  Exit code:    1
--------------------------------------------------------------------------
slurmstepd: error: task_p_post_term: rmdir(/sys/fs/cgroup/cpuset/slurm23750962/slurm23750962.4294967294_0) failed Device or resource busy
